### PR TITLE
Updated Docker dependencies

### PR DESCRIPTION
**Pull request by damianszczepanik**

### CODE REVIEW

**Comment by damianszczepanik** [comment]
Patch dependencies have been updated. Tried to make same with minor but then build start failing.

Later I found that for the same commit `Build and test` stage is failing randomly (see build history). I guess  this is because of  tests which exits with code error 1 but without error message. Can you fix it @amerkurev

**Comment by damianszczepanik** [comment]
@amerkurev can you review and merge this change?

**Comment by amerkurev** [comment]
@damianszczepanik all done, I've merged your pull request. Although its value is not particularly high, to be frank.

**Comment by damianszczepanik** [comment]
> @damianszczepanik all done, I've merged your pull request. Although its value is not particularly high, to be frank.

This is true. I'm going to update also other dependencies and hope you can perform new release after all.
Thanks!

**Pull request merged**
